### ISSUE TITLE
Add miniply to the benchmark?

### ISSUE THREAD

**Issue by vilya** [mhalber/ply_io_benchmark#1]
Hi, 

I've written a new PLY parser called miniply (https://github.com/vilya/miniply). Would you be willing to add it to your benchmark? I'd be happy to submit a pull request.

Great work on the benchmark by the way!

**Comment by mhalber** [comment]
Somehow I was not notified by github about this... 
Apologies that it took so much time - miniply is now part of the benchmark! 
It performs extremely well, great work!
