### ISSUE TITLE
Comparison with libplyxx

### ISSUE THREAD

**Issue by jaquilio** [mhalber/ply_io_benchmark#5]
Thanks for the comparison between different libraries!
Is there any particular reason you left out libplyxx (https://github.com/srajotte/libplyxx)? Do you have any thoughts about the pros and cons of that library?

**Comment by mhalber** [comment]
The only reason is that I was not aware of it existing :D

Thank you for pointing me to it, I will see about adding it and running the benchmark. Might be a while before I get around to it though.
